events { 
    worker_connections 1024; 
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    client_max_body_size 200M;

    upstream frontend_upstream {
        server frontend:3000;
    }

    upstream backend_upstream {
        server backend:5000;
    }

    server {
        listen 80;
        server_name techdaily.duckdns.org _;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # Backend API, Uploads and Health
        location /api/ {
            proxy_pass http://backend_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /health {
            proxy_pass http://backend_upstream;
            proxy_set_header Host $host;
        }

        location /uploads/ {
            proxy_pass http://backend_upstream;
            proxy_set_header Host $host;
        }

        # Frontend Nuxt Nitro SSR
        location / {
            proxy_pass http://frontend_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
